services:
  - type: web
    name: scanner-tool
    env: python
    repo: https://github.com/deanjroach84/My-flask-app.git
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
