services:
  - type: web
    name: scanner-tool
    env: python
    repo: https://github.com/deanjroach84/My-flask-app.git
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-super-secret-key
