services:
  - type: web
    name: ScannerTool
    env: python
    repo: https://github.com/deanjroach84/My-flask-app.git
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: ""
        # value: d0e24c18990ede4030506468331087c351d8d775d276597e7fc8035360f30059
        # Value is set securely in the Render dashboard.
        # d0e24c18990ede4030506468331087c351d8d775d276597e7fc8035360f30059
