services:
  - type: web
    name: ScannerTool
    env: python
    repo: https://github.com/deanjroach84/My-flask-app.git
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        # Value is set securely in the Render dashboard.
